### ISSUE TITLE
Support generate bootable AWS AMI image?

### ISSUE THREAD

**Issue by tmpm697** [nosada/mkosi-files#10]
Just ask, I work with aws services, I find it very fast and convenient to use mkosi to generate image used to spin container.

Is there away to use same method for generate image that compatible to use to upload to aws ami and use to spin up aws ec2 instance?

I can think it will require bios/mbr instead of UEFI.

Basically I want to generate latest image of ubuntu 20.04 with some custom configs and packages and upload to ec2 ami to use for spinning up ec2 instance. (similar to `packer`)

**Comment by nosada** [comment]
You may want to fork this repository or use mkosi directly to build what you want.
Currently I have no plan to support AWS AMI on this repository because I don't use AWS.
