### ISSUE TITLE
Folder for gaming using nspawn container?

### ISSUE THREAD

**Issue by tmpm697** [nosada/mkosi-files#11]
We have guispawn folder but how to have nspawn container that completely support steam game (maybe lutris for ease management)?

I've read some interesting topic [here](https://bbs.archlinux.org/viewtopic.php?id=236714) but not fully try to run steam games via nspawn container.

**Comment by nosada** [comment]
Because I don't have any motivation to play steam game, there's no plan to support it in this repository.
You can fork this repository and try to do that, as I'd answered to you for other topic in https://github.com/nosada/mkosi-files/issues/10.
