### ISSUE TITLE
sudo: unable to execute /usr/sbin/bash: Permission denied

### ISSUE THREAD

**Issue by tmpm697** [nosada/mkosi-files#12]
steps:
```
git clone <repo>
cd <repo>
sudo ./update-nspawn-images guispawn
sudo: unable to execute /usr/sbin/bash: Permission denied
```

I got above error when try to build guispawn, do you have same error?

**Comment by nosada** [comment]
No, I haven't had errors you reported.
It'd be occured by your environment, because `sudo` in yours says `Permission denied` when running `/usr/sbin/bash`.

This may be sudo / bash issues, not by `update-nspawn-images`.
