### ISSUE TITLE
No audio on firefox with guispawn?

### ISSUE THREAD

**Issue by tmpm697** [nosada/mkosi-files#13]
Hi, I just start guispawn and try out if audio on firefox works, but it doesn't work. I pretty much use the default configuration from repo.

aplay -l does not show any devices under nspawn container that shows list of devices on host.

I use pulseaudio under host and connect bluetooth speark via pulseaudio-bluetooth, I have two packages on hosts:
```
pulseaudio-alsa
pulseaudio-bluetooth
```

These packages also avail under container.
The mounting of /dev/snd rw from host should give container all access to hosts audio and does not need any special step afaikto have audio to work on container but somehow I still does not have sound .

How do you handle audio under nspawn?

**Comment by nosada** [comment]
First of all, I've not tested Firefox on `guispawn`. Use it at your own risk.

I'm using PulseAudio too, configured simply following https://wiki.archlinux.org/index.php/PulseAudio, and I can get sound from Chromium, Tor browser and Firefox (additionally installed for testing) without any actions.

All I that I've done is in this repo. I can't reproduce your issue.

> aplay -l does not show any devices under nspawn container that shows list of devices on host.

Me too:
```
[root@guispawn ~]# aplay -l
aplay: device_list:274: no soundcards found...
```

> I have two packages on hosts:
> ```
> pulseaudio-alsa
> pulseaudio-bluetooth
> ```

My packages on host (note that I'm using KDE):
```
$ pacman -Qs pulseaudio
local/libcanberra-pulse 0.30+2+gc0620e4-3
    PulseAudio plugin for libcanberra
local/plasma-pa 5.21.4-1 (plasma)
    Plasma applet for audio volume management using PulseAudio
local/pulseaudio 14.2-3
    A featureful, general-purpose sound server
local/pulseaudio-alsa 1:1.2.2-2
    ALSA Configuration for PulseAudio
local/pulseaudio-bluetooth 14.2-3
    Bluetooth support for PulseAudio
local/pulseaudio-qt 1.2-2
    Qt bindings for libpulse
```

> These packages also avail under container.

I don't install any PulseAudio packages, which is a default state of `guispawn`.
In avobe I used `aplay` (provided `alsa-utils` in Arch) but it'd been installed just only for testing. It seems to be no matter with / without it.

If you could resolve your issue, PRs are welcome!
