### ISSUE TITLE
mstdnspawn: Typo in *container* in info message

### ISSUE THREAD

**Issue by paulmenzel** [nosada/mkosi-files#16]
https://github.com/nosada/mkosi-files/blob/63ef3b987da98e106cc9b2f218951ee5c98dfa40/mstdnspawn/mkosi.finalize.chroot#L63

containt → container?

**Comment by nosada** [comment]
@paulmenzel Fixed by https://github.com/nosada/mkosi-files/pull/17. Thank you for reporting!
