### ISSUE TITLE
Can't get builder shell?

### ISSUE THREAD

**Issue by tmpm697** [nosada/mkosi-files#8]
I build `buildspawn` with default as in your repo and try to get builder shell with:
```
sudo machinectl shell builder@buildspawn
Connected to machine buildspawn. Press ^] three times within 1s to exit session.

Connection to machine buildspawn terminated.
```
Did you face the same problem? I can't get `builder` shell.

**Comment by tmpm697** [comment]
I can get shell of `root` user ok.

**Comment by nosada** [comment]
I haven't faced that... For me it works correctly:
```
$ sudo machinectl shell builder@buildspawn
Connected to machine buildspawn. Press ^] three times within 1s to exit session.
[builder@buildspawn ~]$
```

How about `journalctl -u systemd-nspawn@buildspawn`?

**Comment by tmpm697** [comment]
Output of `journalctl -u systemd-nspawn@buildspawn`: [systemd-nspawn log](https://pastebin.pl/view/717ae643)

`systemd-networkd` seems to fail several times and end up fail.

**Comment by nosada** [comment]
Thank you. It seems your log is same to that in #6 you provided, so I think they might be same problem.
I want to merge this issue to #6.
(But I don't have any solutions now as I said there...)
